services:
  - type: web
    name: reddit-restaurant-mapper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader -d /app/nltk_data punkt averaged_perceptron_tagger maxent_ne_chunker words
    startCommand: gunicorn wsgi:app
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false