services:
- type: web
  name: reddit-restaurant-mapper
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn main:app
  envVars:
    - key: REDDIT_CLIENT_ID
      sync: false
    - key: REDDIT_CLIENT_SECRET
      sync: false
    - key: GOOGLE_MAPS_API_KEY
      sync: false
    - key: ANTHROPIC_API_KEY
      sync: false